export 'package:widget_app/presentation/screens/app_tutorial/app_tutorial_screen.dart';
export 'package:widget_app/presentation/screens/buttons/butons_screen.dart';
export 'package:widget_app/presentation/screens/cards/cards_screen.dart';
export 'package:widget_app/presentation/screens/home/home_screen.dart';
export 'package:widget_app/presentation/screens/infinite_scroll/infiniti_scroll_screen.dart';
export 'package:widget_app/presentation/screens/progress/progress_screen.dart';
export 'package:widget_app/presentation/screens/snackbar/snackbar_screen.dart';
export 'package:widget_app/presentation/screens/ui_controls/ui_controls_screen.dart';
export 'package:widget_app/presentation/screens/animated/animated_screeen.dart';